name: SGK SUT Guncelleyici

on:
  schedule:
    - cron: '0 0 * * *' # Her gece 00:00'da otomatik çalışır
  workflow_dispatch: # Bu satır "Run workflow" butonunu aktif eder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları çek
        uses: actions/checkout@v3
        
      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Kütüphaneleri yükle
        run: |
          pip install requests beautifulsoup4 pandas openpyxl
          
      - name: Botu çalıştır
        run: python bot.py
        
      - name: Değişiklikleri kaydet
        run: |
          git config --global user.name 'SUT Botu'
          git config --global user.email 'bot@sut.com'
          git add .
          git commit -m "SGK Otomatik Taslak Güncelleme" || echo "Değişiklik yok"
          git push
