name: SGK SUT Guncelleyici

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları çek
        uses: actions/checkout@v3
        
      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Kütüphaneleri yükle
        run: |
          pip install requests beautifulsoup4 pandas openpyxl
          
      - name: Botu çalıştır
        run: python bot.py
        
      - name: Değişiklikleri kaydet
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add taslak_kurallar.json
          git commit -m "SGK Taslak Guncellendi" || echo "Degisiklik yok"
          git push
