name: SUT-Bot
on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dosya yazma yetkisini zorla açar
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v3
        with:
          persist-credentials: true # Yetkiyi işlem boyunca saklar

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        run: pip install requests beautifulsoup4 pandas openpyxl

      - name: Botu Çalıştır
        run: python bot.py

      - name: Değişiklikleri Kaydet ve Pushla
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "SGK SUT Verisi Guncellendi"
          file_pattern: 'taslak_kurallar.json' # Sadece bu dosyayı yükle
